global.NL=require('../src/engine.js'); global.window=undefined;
const SB=require('../src/sandbox.js');
const net=SB.example(); const T=SB.testApi(net);
const id=h=>Object.keys(net.devs).find(k=>net.devs[k].cfg.hostname===h);
const pc=net.devs[id('PC-101')], srv=net.devs[id('SRV-HW01')];
const sess=NL.newSess();
const show=(l,r)=>console.log(l.padEnd(34),typeof r==='string'?r.split('\n')[0]:JSON.stringify(r).slice(0,150));
show('DNS web.lab.local',T.resolve(pc,'web.lab.local'));
show('HTTP http://web.lab.local',T.httpGet(pc,'http://web.lab.local'));
show('HTTP ip direkt',T.httpGet(pc,'10.10.0.11'));
show('HTTPS (aus)',T.httpGet(pc,'https://web.lab.local'));
srv.svc.http.https=true; show('HTTPS (an)',T.httpGet(pc,'https://web.lab.local'));
show('unbekannter Name',T.resolve(pc,'gibts.nicht'));
srv.svc.dns.on=false; show('DNS aus',T.resolve(pc,'web.lab.local')); srv.svc.dns.on=true;
srv.svc.http.on=false; show('HTTP aus',T.httpGet(pc,'10.10.0.11')); srv.svc.http.on=true;
show('cmd ping name',T.hostLine(pc,sess,'ping web.lab.local'));
show('cmd nslookup',T.hostLine(pc,sess,'nslookup storage.lab.local'));
show('cmd curl',T.hostLine(pc,sess,'curl http://web.lab.local'));
// DHCP: new server + new PC in VLAN 30 via free ports of ACC-01
const acc=id('SW-ACC-01'); const s2=T.addDev('HW-1288H-V5',0,0,'DHCP-SRV'), p2=T.addDev('PC',0,0,'PC-NEU');
net.links.push({a:s2,ap:'eth0',b:acc,bp:'GigabitEthernet1/0/5',cable:'cu'}); net.links.push({a:p2,ap:'eth0',b:acc,bp:'GigabitEthernet1/0/6',cable:'cu'});
const run=(i,l)=>{const d=net.devs[i],s=NL.newSess();[...(NL.isHost(d)?[]:['en','conf t']),...l,...(NL.isHost(d)?[]:['end'])].forEach(x=>NL.exec(net,i,s,x))};
run(acc,['interface range g1/0/5 - 6','switchport mode access','switchport access vlan 30']);
run(s2,['ip 10.30.0.5/24 10.30.0.1']);
const D=net.devs[s2].svc.dhcp; D.on=true; D.gw='10.30.0.1'; D.dns='10.10.0.11'; D.start='10.30.0.100'; D.mask='255.255.255.0'; D.max=5;
show('DHCP Client Lease',T.dhcpRequest(net.devs[p2]));
console.log('   PC-NEU ip',NL.hip(net.devs[p2],'eth0'),'gw',net.devs[p2].cfg.gw,'dns',net.devs[p2].cfg.dns);
show('PC-NEU ping SRV',T.hostLine(net.devs[p2],NL.newSess(),'ping 10.10.0.11'));
show('PC-NEU http via DNS',T.httpGet(net.devs[p2],'web.lab.local'));
run(acc,['interface g1/0/6','switchport access vlan 99']);
show('DHCP falsches VLAN',T.dhcpRequest(net.devs[p2]));
